### ISSUE TITLE
[enhancement]Increasing Number of Sides

### ISSUE THREAD

**Issue by ctaylor-c172** [AdamTyler/react-dice-complete#11]
Hi, great project!

How could I go about increasing the number of sides on the dice..? Perhaps to 10
Would it be a matter of increasing the number of f(num)Style and changing sides: to e.g 10
Thanks in advance.

**Comment by AdamTyler** [comment]
Thats a pretty cool idea.
I think the main challenge then would be the geometry in the animation.

**Comment by AdamTyler** [comment]
This change is beyond the scope of this library as it would be a large load of work
