### ISSUE TITLE
Support for react native

### ISSUE THREAD

**Issue by stardev24** [AdamTyler/react-dice-complete#17]
Will it support react native?
Any future plans for this in road map?

**Comment by AdamTyler** [comment]
I'm currently looking into supporting React Native but from my understanding it isn't a trivial change since the current library is heavily reliant on some DOM features.

So as of right now I'm not sure if this library will support React Native but I will update here when I figure out a way forward

**Comment by AdamTyler** [comment]
React Native support is beyond the scope of this project
