### ISSUE TITLE
Need react-dice-complete Library for React Native

### ISSUE THREAD

**Issue by amourya-systango** [AdamTyler/react-dice-complete#3]
Can you please provide react-dice-complete library for react native.

Thanks

**Comment by AdamTyler** [comment]
Is this something you are still looking for? I might have some free time soon to look into this

**Comment by gHashTag** [comment]
@AdamTyler Please Adam, it is very necessary, otherwise you have to do it through webview.

**Comment by StuartMorris0** [comment]
@AdamTyler  @gHashTag How do you get this working without it? I get the following:

 Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `react-dice-complete/dist/react-dice-complete.css` from `PATHTOAPPFILE`: Module `react-dice-complete/dist/react-dice-complete.css` does not exist in the Haste module map

**Comment by AdamTyler** [comment]
@StuartMorris0 converting this library to be used in React Native isn't a trivial change. I will have to rewrite large portions of the code. I've started to try and see how far I get but don't know if I'm going to take the time necessary to do so.

**Comment by VED-StuartMorris** [comment]
Thanks @AdamTyler I had to come up with a different solution, so we basically had an image of a dice that we animated, generated the end result, and ensured the end result image matched the dice number expected. Etc...

**Comment by AdamTyler** [comment]
React Native support is beyond the scope of this project
