### ISSUE TITLE
PropTypes Deprecation

### ISSUE THREAD

**Issue by Serexx** [AdamTyler/react-dice-complete#5]
Greetings, thanks for the work on this, made life easier :-)

React is complaining about the deprecated internal PropTypes (replaced by the separate 'prop-types' package) in Die.js and ReactDice.js 

I'd rather not fork it for my current project but will if you don't want to change the master?

**Comment by Serexx** [comment]
I went ahead and forked it and made the change.

Also fixed a bug in die.js where this.die.classList='die' was throwing in Edge as classList is actually read-only even tho Chrome and Firefox allow it. Changed it to this.die.className='die'

My fork is [here](https://github.com/Serexx/react-dice-complete) if anyone wants it

**Comment by AdamTyler** [comment]
PR was merged
