### ISSUE TITLE
Support React 18

### ISSUE THREAD

**Issue by timB73** [AdamTyler/react-dice-complete#66]
Hi, I've just upgraded my project to React 18 and found the dice has broken. Everything works except the value returned on the rollDone callback doesn't match the value of the face of the dice.  Any possibility this could get fixed? Thanks.

Edit: it looks like the value being returned is the previous rolled value.

**Comment by AdamTyler** [comment]
@timB73 thanks for the issue writeup. I am planning to update a good portion of dependencies for this project soon as many of them have gone out of date.
I will update React as part of this effort

**Comment by timB73** [comment]
That's great news, thank you! I couldn't find any other libraries as good as this.

**Comment by josegamboa** [comment]
Hi @AdamTyler ,

Thanks for maintaining this library. Is there any plans for exporting the types for Typescript support?

I would like to use this one on a React18 project, but not  sure  when will be release React18 support.

Thanks...

**Comment by AdamTyler** [comment]
Support for React 18 has been added and will be available in an upcoming release.

@josegamboa can you create an issue specifically to add Typescript support. I want to add that in an upcoming release

**Comment by AdamTyler** [comment]
React 18 is available as of [v2.0.2](https://github.com/AdamTyler/react-dice-complete/releases/tag/v2.0.2)
