### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by josegamboa** [AdamTyler/react-dice-complete#73]
Hi Guys,

Thanks for maintaining this component. is there any change you guys add Typescript support?

Related issue: https://github.com/AdamTyler/react-dice-complete/issues/66

Thanks...

**Comment by AdamTyler** [comment]
Typescript support was added in #74 .
Will be pulled into the next release!

**Comment by AdamTyler** [comment]
Typescript support is available in [v2.1.0](https://github.com/AdamTyler/react-dice-complete/releases/tag/v2.1.0)
